import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";
import ThemeSetter from "./components/ThemeSetter";
import Header from "./components/Header";

const notoSansLocal = localFont({
  src: [
    {
      path: "./fonts/NotoSansKR-Thin.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Black.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Bold.woff2",
    },
    {
      path: "./fonts/NotoSansKR-DemiLight.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Light.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Medium.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Regular.woff2",
    },
  ],
  variable: "--font-noto-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${notoSansLocal.variable}`}>
      <body className="font-sans w-[100dvw] min-h-[100dvh] h-[100dvh] background transition-colors overflow-hidden">
        {children}
        {/* <Header />
        <main className="w-full h-[calc(100dvh_-_4rem)] flex flex-col items-center">{children}</main> */}
      </body>

      <ThemeSetter />
    </html>
  );
}
