import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";
import ThemeSetter from "./_components/ThemeSetter";
import Header from "./_components/Header";

const notoSansLocal = localFont({
  src: [
    {
      path: "./fonts/NotoSansKR-Thin.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Black.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Bold.woff2",
    },
    {
      path: "./fonts/NotoSansKR-DemiLight.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Light.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Medium.woff2",
    },
    {
      path: "./fonts/NotoSansKR-Regular.woff2",
    },
  ],
  variable: "--font-noto-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${notoSansLocal.variable}`}>
      <body className="font-sans w-screen min-h-[100dvh] h-[100dvh] bg-slate-50 dark:bg-gray-950 transition-colors">
        <Header />
        <main className="w-full h-[calc(100dvh_-_3rem)]">{children}</main>
      </body>

      <ThemeSetter />
    </html>
  );
}
